config/routes.rb
Rails.application.routes.draw do
  root to: 'stories#top'
  get 'stories/:id', to:'stories#show', as: :story
  get 'comments/:id', to: 'comments#show', as: :comment
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #all controllers have access now
  def client
    @client ||= Hackernews::Client.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def show 
        @comment = client.item(params[:id])
        @comments = (@comment['kids'] || []).map do |kid|
            client.item(kid)
        end
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    def top
        @start = (params[:start] || 0).to_i
        @per_page = (params[:per_page] || 10).to_i
        @per_page = [@per_page, 20].min #max 20 per page

        @stories = client.topstories(@start, @per_page) #passing 2 parameters to assit with pagination
    end

    def show
        #shows story and comment details
        @story = client.item(params[:id])
        @comments = (@story['kids'] || []).map do |comment| #incase there is no comments use [] to avoid an error
            client.item(comment)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
 <!--following DRY principle -->

<div class="media-mb-3">
  <div class="media-body">
    <span class="text-muted">
     <%= comment['by'] %> <%= time_ago_in_words(comment['time']) %> ago
     | <%= link_to "#{comment.fetch('kids', []).count} responses", comment_path(comment['id']) %>
    </span> 

    <p><%= sanitize comment['text'] %></p>
  </div>
</div>

<hr>

app/views/comments/show.html.erb
<% render partial: 'comment', object: @comment %>
<h4>Reponses</h4>
<%= render partial: 'comment',collection: @comments %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Hacker News API</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
  <div class="container">
    <h1><%= link_to 'Hackernews', root_path %></h1>
    
    <%= yield %>
  </div>
  
  </body>
</html>

app/views/stories/_story.html.erb
 <!--following DRY principle -->
 
 <div class="media mb-3">
    <div class="media-body">
      <h5 class="mt-0 mb-1">
        <a href="<%= story['url'] %>"><%= story['title'] %></a>
      </h5>

      <%= story['score'] %> points
      by <%= story['by'] %>
      <%= time_ago_in_words(story['time']) %> ago
      | <%= link_to "#{story['descendants']} comments", story_path(story['id']) %>

    </div>
  </div>

app/views/stories/show.html.erb
<%= render partial: 'story', object: @story %>

<%= render partial: 'comments/comment', collection: @comments %>

app/views/stories/top.html.erb
<!--loop through all current stories-->
<% @stories.each do |story| %>
  <%= render partial: 'story', collection: @stories %>    
<% end %>

<nav>
  <ul class="pagination justify-content-center">
    <li class="page-item <%='disabled' if @start == 0 %>">
      <%= link_to 'Previous', root_path(start: @start - @per_page), class:'page-link' %>
    </li>
    <li class="page-item">
      <%= link_to 'Next', root_path(start: @start + @per_page), class: 'page-link' %>
    </li>
  </ul>
 </nav>